"""baseline pre-auth schema

Revision ID: 9ff9063ce318
Revises: 
Create Date: 2026-06-12 14:17:02.433608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff9063ce318'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=False),
    sa.Column('transports', sa.String(length=200), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webauthn_credentials_credential_id'), 'webauthn_credentials', ['credential_id'], unique=True)
    op.create_index(op.f('ix_webauthn_credentials_user_id'), 'webauthn_credentials', ['user_id'], unique=False)
    op.add_column('account_balance_snapshots', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('account_balance_snapshots', 'value_native',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('account_balance_snapshots', 'value_base',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_acct_bal_snap'), table_name='account_balance_snapshots')
    op.create_index(op.f('ix_account_balance_snapshots_user_id'), 'account_balance_snapshots', ['user_id'], unique=False)
    op.create_foreign_key(None, 'account_balance_snapshots', 'users', ['user_id'], ['id'])
    op.add_column('accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('accounts', 'current_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('accounts', 'purchase_price',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('accounts', 'statement_balance',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('accounts', 'original_principal_balance',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('accounts', 'interest_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('accounts', 'monthly_payment',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('accounts', 'balance_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('accounts', 'plan_it_balance',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('accounts', 'overdraft_limit',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'accounts', 'users', ['user_id'], ['id'])
    op.add_column('asset_valuation_snapshots', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('asset_valuation_snapshots', 'value_native',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('asset_valuation_snapshots', 'value_base',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_asset_valuation_snapshots_user_id'), 'asset_valuation_snapshots', ['user_id'], unique=False)
    op.create_foreign_key(None, 'asset_valuation_snapshots', 'users', ['user_id'], ['id'])
    op.add_column('asset_valuations', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('asset_valuations', 'value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_valuation_account_date'), table_name='asset_valuations')
    op.create_index(op.f('ix_asset_valuations_user_id'), 'asset_valuations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'asset_valuations', 'users', ['user_id'], ['id'])
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_categories_user_id'), 'categories', ['user_id'], unique=False)
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    op.add_column('category_rules', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_cat_rule_pattern'), table_name='category_rules')
    op.create_index(op.f('ix_category_rules_user_id'), 'category_rules', ['user_id'], unique=False)
    op.create_foreign_key(None, 'category_rules', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_fx_pair_date'), table_name='currency_rates')
    op.alter_column('deleted_transactions', 'amount_base',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('deleted_transactions', 'exchange_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('deleted_transactions', 'balance_after',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('deleted_transactions', 'classification_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('financial_document_lines', 'amount_native',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.add_column('financial_documents', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_fin_doc_prop'), table_name='financial_documents')
    op.drop_index(op.f('ix_fin_doc_type_date'), table_name='financial_documents')
    op.create_index(op.f('ix_financial_documents_user_id'), 'financial_documents', ['user_id'], unique=False)
    op.create_foreign_key(None, 'financial_documents', 'users', ['user_id'], ['id'])
    op.add_column('household_snapshots', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('household_snapshots', 'total_assets_base',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('household_snapshots', 'total_liabilities_base',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('household_snapshots', 'net_worth_base',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_household_snap'), table_name='household_snapshots')
    op.create_index(op.f('ix_household_snapshots_user_id'), 'household_snapshots', ['user_id'], unique=False)
    op.create_foreign_key(None, 'household_snapshots', 'users', ['user_id'], ['id'])
    op.add_column('import_batches', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_import_batches_user_id'), 'import_batches', ['user_id'], unique=False)
    op.create_foreign_key(None, 'import_batches', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_instrument_symbol'), table_name='instruments')
    op.add_column('liability_balance_snapshots', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('liability_balance_snapshots', 'value_native',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('liability_balance_snapshots', 'value_base',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.create_index(op.f('ix_liability_balance_snapshots_user_id'), 'liability_balance_snapshots', ['user_id'], unique=False)
    op.create_foreign_key(None, 'liability_balance_snapshots', 'users', ['user_id'], ['id'])
    op.alter_column('paycheck_stubs', 'gross_pay',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'net_pay',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'federal_tax',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'state_tax',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'local_tax',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'social_security',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'medicare',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'retirement_401k',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'health_insurance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'dental_insurance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'vision_insurance',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'hsa_contribution',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'other_deductions',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'ytd_gross',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('paycheck_stubs', 'ytd_net',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('paycheck_stubs', 'ytd_federal_tax',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('paycheck_stubs', 'ytd_state_tax',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('paycheck_stubs', 'ytd_retirement_401k',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_paycheck_account_date'), table_name='paycheck_stubs')
    op.alter_column('payment_decompositions', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('payment_decompositions', 'amount_base',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_payment_decomp_txn'), table_name='payment_decompositions')
    op.add_column('plan_it_plans', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_plan_it_plans_user_id'), 'plan_it_plans', ['user_id'], unique=False)
    op.create_foreign_key(None, 'plan_it_plans', 'users', ['user_id'], ['id'])
    op.alter_column('position_lots', 'cost_basis_total',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_position_acct_inst'), table_name='position_lots')
    op.alter_column('price_snapshots', 'price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=6),
               existing_nullable=False)
    op.drop_index(op.f('ix_price_inst_date'), table_name='price_snapshots')
    op.add_column('property_pnl_snapshots', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('property_pnl_snapshots', 'total_income',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('property_pnl_snapshots', 'total_expense',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('property_pnl_snapshots', 'owner_draw',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('property_pnl_snapshots', 'liability_adjustment',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('property_pnl_snapshots', 'net_operating_income',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('property_pnl_snapshots', 'net_cash_flow',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_pnl_prop_period'), table_name='property_pnl_snapshots')
    op.create_index(op.f('ix_property_pnl_snapshots_user_id'), 'property_pnl_snapshots', ['user_id'], unique=False)
    op.create_foreign_key(None, 'property_pnl_snapshots', 'users', ['user_id'], ['id'])
    op.alter_column('reconciliation_groups', 'tolerance_base',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('reconciliation_groups', 'residual_base',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('reconciliation_groups', 'reconciliation_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('reconciliation_groups', 'fx_rate_used',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('reconciliation_members', 'allocated_amount_native',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('reconciliation_members', 'allocated_amount_base',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_recon_member_group'), table_name='reconciliation_members')
    op.drop_index(op.f('ix_recon_member_txn'), table_name='reconciliation_members')
    op.add_column('rental_properties', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rental_properties_user_id'), 'rental_properties', ['user_id'], unique=False)
    op.create_foreign_key(None, 'rental_properties', 'users', ['user_id'], ['id'])
    op.add_column('scheduled_payments', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_sched_pay_account'), table_name='scheduled_payments')
    op.drop_index(op.f('ix_sched_pay_active'), table_name='scheduled_payments')
    op.create_index(op.f('ix_scheduled_payments_user_id'), 'scheduled_payments', ['user_id'], unique=False)
    op.create_foreign_key(None, 'scheduled_payments', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_stock_div_acct'), table_name='stock_dividends')
    op.drop_index(op.f('ix_stock_div_inst'), table_name='stock_dividends')
    op.drop_index(op.f('ix_stock_trade_acct'), table_name='stock_trades')
    op.drop_index(op.f('ix_stock_trade_dedup'), table_name='stock_trades')
    op.drop_index(op.f('ix_stock_trade_inst'), table_name='stock_trades')
    op.alter_column('transaction_splits', 'amount_native',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('transaction_splits', 'amount_base',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_split_doc_line'), table_name='transaction_splits')
    op.drop_index(op.f('ix_split_spend'), table_name='transaction_splits')
    op.drop_index(op.f('ix_split_txn'), table_name='transaction_splits')
    op.create_index(op.f('ix_transaction_splits_document_line_id'), 'transaction_splits', ['document_line_id'], unique=False)
    op.create_foreign_key(None, 'transaction_splits', 'financial_document_lines', ['document_line_id'], ['id'])
    op.alter_column('transactions', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.alter_column('transactions', 'amount_base',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('transactions', 'balance_after',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('transactions', 'transfer_dismissed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('transactions', 'classification_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index(op.f('ix_txn_account_amount'), table_name='transactions')
    op.drop_index(op.f('ix_txn_account_date'), table_name='transactions')
    op.drop_index(op.f('ix_txn_category'), table_name='transactions')
    op.drop_index(op.f('ix_txn_event_type'), table_name='transactions')
    op.drop_index(op.f('ix_txn_fin_doc'), table_name='transactions')
    op.drop_index(op.f('ix_txn_import_batch'), table_name='transactions')
    op.drop_index(op.f('ix_txn_transfer'), table_name='transactions')
    op.create_index(op.f('ix_transactions_financial_document_id'), 'transactions', ['financial_document_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'financial_documents', ['financial_document_id'], ['id'])
    op.alter_column('transfer_links', 'amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=False)
    op.add_column('user_profile', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('user_profile', 'recurring_min_confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.5)'))
    op.alter_column('user_profile', 'recurring_min_amt_consistency',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.3)'))
    op.alter_column('user_profile', 'recurring_fixed_amt_consistency',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.85)'))
    op.create_index(op.f('ix_user_profile_user_id'), 'user_profile', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_profile_user_id', 'user_profile', ['user_id'])
    op.create_foreign_key(None, 'user_profile', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='foreignkey')
    op.drop_constraint('uq_user_profile_user_id', 'user_profile', type_='unique')
    op.drop_index(op.f('ix_user_profile_user_id'), table_name='user_profile')
    op.alter_column('user_profile', 'recurring_fixed_amt_consistency',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.85)'))
    op.alter_column('user_profile', 'recurring_min_amt_consistency',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.3)'))
    op.alter_column('user_profile', 'recurring_min_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.5)'))
    op.drop_column('user_profile', 'user_id')
    op.alter_column('transfer_links', 'amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_financial_document_id'), table_name='transactions')
    op.create_index(op.f('ix_txn_transfer'), 'transactions', ['is_transfer', 'transfer_link_id'], unique=False)
    op.create_index(op.f('ix_txn_import_batch'), 'transactions', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_txn_fin_doc'), 'transactions', ['financial_document_id'], unique=False)
    op.create_index(op.f('ix_txn_event_type'), 'transactions', ['event_type'], unique=False)
    op.create_index(op.f('ix_txn_category'), 'transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_txn_account_date'), 'transactions', ['account_id', 'date'], unique=False)
    op.create_index(op.f('ix_txn_account_amount'), 'transactions', ['account_id', 'amount'], unique=False)
    op.alter_column('transactions', 'classification_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('transactions', 'transfer_dismissed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('transactions', 'balance_after',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('transactions', 'amount_base',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('transactions', 'amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_constraint(None, 'transaction_splits', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_splits_document_line_id'), table_name='transaction_splits')
    op.create_index(op.f('ix_split_txn'), 'transaction_splits', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_split_spend'), 'transaction_splits', ['counts_as_true_spend', 'spend_type'], unique=False)
    op.create_index(op.f('ix_split_doc_line'), 'transaction_splits', ['document_line_id'], unique=False)
    op.alter_column('transaction_splits', 'amount_base',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('transaction_splits', 'amount_native',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.create_index(op.f('ix_stock_trade_inst'), 'stock_trades', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_stock_trade_dedup'), 'stock_trades', ['ibkr_dedup_key'], unique=False)
    op.create_index(op.f('ix_stock_trade_acct'), 'stock_trades', ['account_id', 'trade_date'], unique=False)
    op.create_index(op.f('ix_stock_div_inst'), 'stock_dividends', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_stock_div_acct'), 'stock_dividends', ['account_id', 'pay_date'], unique=False)
    op.drop_constraint(None, 'scheduled_payments', type_='foreignkey')
    op.drop_index(op.f('ix_scheduled_payments_user_id'), table_name='scheduled_payments')
    op.create_index(op.f('ix_sched_pay_active'), 'scheduled_payments', ['active', 'next_due_date'], unique=False)
    op.create_index(op.f('ix_sched_pay_account'), 'scheduled_payments', ['account_id', 'next_due_date'], unique=False)
    op.drop_column('scheduled_payments', 'user_id')
    op.drop_constraint(None, 'rental_properties', type_='foreignkey')
    op.drop_index(op.f('ix_rental_properties_user_id'), table_name='rental_properties')
    op.drop_column('rental_properties', 'user_id')
    op.create_index(op.f('ix_recon_member_txn'), 'reconciliation_members', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_recon_member_group'), 'reconciliation_members', ['group_id'], unique=False)
    op.alter_column('reconciliation_members', 'allocated_amount_base',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('reconciliation_members', 'allocated_amount_native',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('reconciliation_groups', 'fx_rate_used',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('reconciliation_groups', 'reconciliation_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('reconciliation_groups', 'residual_base',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('reconciliation_groups', 'tolerance_base',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_constraint(None, 'property_pnl_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_property_pnl_snapshots_user_id'), table_name='property_pnl_snapshots')
    op.create_index(op.f('ix_pnl_prop_period'), 'property_pnl_snapshots', ['rental_property_id', 'statement_date'], unique=False)
    op.alter_column('property_pnl_snapshots', 'net_cash_flow',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('property_pnl_snapshots', 'net_operating_income',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('property_pnl_snapshots', 'liability_adjustment',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('property_pnl_snapshots', 'owner_draw',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('property_pnl_snapshots', 'total_expense',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('property_pnl_snapshots', 'total_income',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('property_pnl_snapshots', 'user_id')
    op.create_index(op.f('ix_price_inst_date'), 'price_snapshots', ['instrument_id', 'as_of_date'], unique=False)
    op.alter_column('price_snapshots', 'price',
               existing_type=sa.Numeric(precision=18, scale=6),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.create_index(op.f('ix_position_acct_inst'), 'position_lots', ['account_id', 'instrument_id', 'as_of_date'], unique=False)
    op.alter_column('position_lots', 'cost_basis_total',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_constraint(None, 'plan_it_plans', type_='foreignkey')
    op.drop_index(op.f('ix_plan_it_plans_user_id'), table_name='plan_it_plans')
    op.drop_column('plan_it_plans', 'user_id')
    op.create_index(op.f('ix_payment_decomp_txn'), 'payment_decompositions', ['transaction_id'], unique=False)
    op.alter_column('payment_decompositions', 'amount_base',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('payment_decompositions', 'amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.create_index(op.f('ix_paycheck_account_date'), 'paycheck_stubs', ['account_id', 'pay_date'], unique=False)
    op.alter_column('paycheck_stubs', 'ytd_retirement_401k',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('paycheck_stubs', 'ytd_state_tax',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('paycheck_stubs', 'ytd_federal_tax',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('paycheck_stubs', 'ytd_net',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('paycheck_stubs', 'ytd_gross',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('paycheck_stubs', 'other_deductions',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'hsa_contribution',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'vision_insurance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'dental_insurance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'health_insurance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'retirement_401k',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'medicare',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'social_security',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'local_tax',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'state_tax',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'federal_tax',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'net_pay',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('paycheck_stubs', 'gross_pay',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_constraint(None, 'liability_balance_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_liability_balance_snapshots_user_id'), table_name='liability_balance_snapshots')
    op.alter_column('liability_balance_snapshots', 'value_base',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('liability_balance_snapshots', 'value_native',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('liability_balance_snapshots', 'user_id')
    op.create_index(op.f('ix_instrument_symbol'), 'instruments', ['symbol'], unique=False)
    op.drop_constraint(None, 'import_batches', type_='foreignkey')
    op.drop_index(op.f('ix_import_batches_user_id'), table_name='import_batches')
    op.drop_column('import_batches', 'user_id')
    op.drop_constraint(None, 'household_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_household_snapshots_user_id'), table_name='household_snapshots')
    op.create_index(op.f('ix_household_snap'), 'household_snapshots', ['as_of_date'], unique=False)
    op.alter_column('household_snapshots', 'net_worth_base',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('household_snapshots', 'total_liabilities_base',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('household_snapshots', 'total_assets_base',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('household_snapshots', 'user_id')
    op.drop_constraint(None, 'financial_documents', type_='foreignkey')
    op.drop_index(op.f('ix_financial_documents_user_id'), table_name='financial_documents')
    op.create_index(op.f('ix_fin_doc_type_date'), 'financial_documents', ['document_type', 'statement_date'], unique=False)
    op.create_index(op.f('ix_fin_doc_prop'), 'financial_documents', ['rental_property_id', 'statement_date'], unique=False)
    op.drop_column('financial_documents', 'user_id')
    op.alter_column('financial_document_lines', 'amount_native',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('deleted_transactions', 'classification_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('deleted_transactions', 'balance_after',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('deleted_transactions', 'exchange_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('deleted_transactions', 'amount_base',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.create_index(op.f('ix_fx_pair_date'), 'currency_rates', ['base_currency', 'quote_currency', 'date'], unique=False)
    op.drop_constraint(None, 'category_rules', type_='foreignkey')
    op.drop_index(op.f('ix_category_rules_user_id'), table_name='category_rules')
    op.create_index(op.f('ix_cat_rule_pattern'), 'category_rules', ['pattern'], unique=False)
    op.drop_column('category_rules', 'user_id')
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_index(op.f('ix_categories_user_id'), table_name='categories')
    op.drop_column('categories', 'user_id')
    op.drop_constraint(None, 'asset_valuations', type_='foreignkey')
    op.drop_index(op.f('ix_asset_valuations_user_id'), table_name='asset_valuations')
    op.create_index(op.f('ix_valuation_account_date'), 'asset_valuations', ['account_id', 'date'], unique=False)
    op.alter_column('asset_valuations', 'value',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('asset_valuations', 'user_id')
    op.drop_constraint(None, 'asset_valuation_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_asset_valuation_snapshots_user_id'), table_name='asset_valuation_snapshots')
    op.alter_column('asset_valuation_snapshots', 'value_base',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('asset_valuation_snapshots', 'value_native',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('asset_valuation_snapshots', 'user_id')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.alter_column('accounts', 'overdraft_limit',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('accounts', 'plan_it_balance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('accounts', 'balance_confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('accounts', 'monthly_payment',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('accounts', 'interest_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('accounts', 'original_principal_balance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('accounts', 'statement_balance',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('accounts', 'purchase_price',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('accounts', 'current_value',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_column('accounts', 'user_id')
    op.drop_constraint(None, 'account_balance_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_account_balance_snapshots_user_id'), table_name='account_balance_snapshots')
    op.create_index(op.f('ix_acct_bal_snap'), 'account_balance_snapshots', ['account_id', 'as_of_date'], unique=False)
    op.alter_column('account_balance_snapshots', 'value_base',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.alter_column('account_balance_snapshots', 'value_native',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.drop_column('account_balance_snapshots', 'user_id')
    op.drop_index(op.f('ix_webauthn_credentials_user_id'), table_name='webauthn_credentials')
    op.drop_index(op.f('ix_webauthn_credentials_credential_id'), table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
